baseURL = "https://barbdev.github.io/site-perso/"
languageCode = "fr"
title = "Site personnel"
theme = "blogTheme"
copyright = "Tous droits réservés - Copyright "

[params]
    author = "Tanguy PORET"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

[[menu.main]]
    name = "Blog"
    title = "Blog"
    weight = 50
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "Accueil"
    title = "Accueil"
    weight = -1
    url = "/"
[[menu.main]]
    name = "Outils"
    title = "Outils"
    identifier = "outils"
    url = "/outils/"
    weight = 0